services:
  resources:
    path: resources

  matchmaking:
    path: matchmaking
    dependsOn:
      - resources
    params:
      apiGatewayRestApiId: ${resources.apiGatewayRestApiId}
      apiGatewayRestApiRootResourceId: ${resources.apiGatewayRestApiRootResourceId}
      cognitoUserPoolArn: ${resources.cognitoUserPoolArn}
      cognitoUserPoolClientId: ${resources.cognitoUserPoolClientId}
      dynamodbTicketTable: ${resources.tableTickets}
      dynamodbTicketTableArn: ${resources.tableTicketsArn}
      dynamodbPlayerTable: ${resources.tablePlayers}
      dynamodbPlayerTableArn: ${resources.tablePlayersArn}
      snsNotificationTopic: ${resources.snsTopicName}
