service: matchingevents

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:BatchWriteItem"
          Resource: ${param:dynamodbTicketTableArn}

functions:
  matchingevents:
    handler: handler.handler
    events:
      - sns: ${param:snsNotificationTopic}
    environment:
      TICKET_TABLE_NAME: ${param:dynamodbTicketTable}
